name: 'Remove prefix from github ref_name'

inputs:
  pref:
    required: true
    type: string
    description: 'Prefix to remove'

outputs:
  image_tag:
    description: "Tag without a prefix"
    value: ${{ steps.prefix_remover.outputs.image_tag }}

runs:
  using: composite
  steps:
    - name: Print Gihub context
      shell: bash
      run: |
        printf '# GitHub context\n' >> $GITHUB_STEP_SUMMARY
        printf '```\n' >> $GITHUB_STEP_SUMMARY
        printf '${{ toJSON(github) }}' | jq >> $GITHUB_STEP_SUMMARY
        printf '\n```' >> $GITHUB_STEP_SUMMARY
    - name: Remove prefix
      id: prefix_remover
      shell: python
      run: |
        from os import environ
        from sys import exit
        ref = '${{ github.ref_name }}'
        pref = '${{ inputs.pref }}'
        tag = ref.removeprefix(pref)
        if tag == ref:
          print(
            f'::error::could not remove prefix {pref}. '
            f'from github reference {ref}'
          )
        # To be able use IMAGE_TAG environment variable
        with open(environ['GITHUB_ENV'], 'a') as f:
          f.write('IMAGE_TAG=' + tag + '\n')
        # To be able use image_tag output value
        with open(environ['GITHUB_OUTPUT'], 'a') as f:
          f.write('image_tag=' + tag + '\n')
