name: 'Test removing of prefix'

on:
  push:
    tags:
      - 'prefix-*'

jobs:
  remove-prefix-and-use-it:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Remove prefix
        id: remove_prefix
        uses: the-tests/gha-tests/.github/workflows/remove_prefix.yaml@dev
        with:
          pref: prefix-

      - name: Use new tag
        uses: the-tests/gha-tests/.github/workflows/use_new_tag.yaml@dev
        with:
          image_tag: steps.remove_prefix.outputs.image_tag
