name: 'Test removing of prefix'

on:
  push:
    tags:
      - 'prefix-*'

jobs:
  remove-prefix-and-use-it:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print files
        shell: bash
        run: |
          tree

      - name: Remove prefix
        id: remove_prefix
        uses: ./.github/workflows/remove_prefix.yaml
        with:
          pref: prefix-

      - name: Use new tag
        uses: ./.github/workflows/use_new_tag.yaml
        with:
          image_tag: steps.remove_prefix.outputs.image_tag
