name: 'Test removing of prefix'

on:
  push:
    tags:
      - 'prefix-*'

jobs:
  remove-prefix-and-use-it:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Remove prefix
        id: remove_prefix
        uses: ./.github/actions/remove_prefix
        with:
          pref: prefix-

      - name: Use new tag
        uses: ./.github/actions/use_new_tag
        with:
          image_tag: ${{ steps.remove_prefix.outputs.image_tag }}
