name: "Get files"

on:
  pull_request:
    branches:
      - dev

jobs:
  get_files:
    runs-on: ubuntu-latest
    name: "GET FILES"
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Modified files
        run: |
          echo "${{ toJSON(github) }}" >> $GITHUB_STEP_SUMMARY
